services:
  app:
    build: .
    container_name: php_app
    depends_on:
      db:
        condition: service_started # Note: Consider adding healthchecks for better control
    volumes:
      - type: bind
        source: /var/www/UserAccessManagement
        target: /var/www/html
      - type: bind
        source: /var/www/UserAccessManagement/files4docker/php.ini
        target: /usr/local/etc/php/php.ini
      # - /var/www/UserAccessManagement/files4docker/php_pdo_sqlsrv_81_ts_x64.dll:/usr/local/etc/php/ext/php_pdo_sqlsrv_81_ts_x64.dll
      # - /var/www/UserAccessManagement/files4docker/php_sqlsrv_81_ts_x64.dll:/usr/local/etc/php/ext/php_sqlsrv_81_ts_x64.dll
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "  composer install --ignore-platform-req=ext-gd --ignore-platform-req=ext-zip || true; && php artisan key:generate &&  php artisan storage:link &&  php artisan migrate --seed &&  php artisan serve --host=0.0.0.0 --port=8000  "
    ports:
      - "8001:8000"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_access
    ports:
      - "5432:5432"
