services:
  app:
    build: .
    container_name: uam_dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    ports:
      - "8001:80"
    command: apache2-foreground

  db:
    image: postgres:16
    container_name: postgres_db_uam
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_access
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_uam:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    build: .
    container_name: uam_queue
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=1 --tries=3 --timeout=90
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"

volumes:
  postgres_db_uam:
