services:
  app:
    build: .
    container_name: uam_dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    ports:
      - "8001:80" # Apache langsung serve port 80 di container
    command: apache2-foreground

  db:
    image: postgres:latest
    container_name: postgres_db_uam
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_access
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_uam:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_db_uam:
